### ISSUE TITLE
Publish gem to rubygems.org ?

### ISSUE THREAD

**Issue by jrnk** [eddietejeda/administrate-field-json#1]
First of all: thanks for making this! We had a need for the same in administrate, so a github search turned up your gem, however would you be able to push this to rubygems.org? Thanks for considering!

**Comment by jrnk** [comment]
Sorry, I just found your opened issue here: https://github.com/thoughtbot/administrate/issues/566 
I'll leave this open for you to decide what to do with it :)

**Comment by eddietejeda** [comment]
I will be pushing to rubygems soon.
