### ISSUE TITLE
Administrate 0.3 Support

### ISSUE THREAD

**Issue by stratigos** [eddietejeda/administrate-field-json#10]
Thanks for producing this gem, I'm having some trouble regarding Administrate treating my JSON attributes as String.

I am unable to use this gem with the latest version of Administrate, however:

```
Bundler could not find compatible versions for gem "administrate":
  In snapshot (Gemfile.lock):
    administrate (= 0.3.0)

  In Gemfile:
    administrate (~> 0.3.0)

    administrate-field-json was resolved to 0.0.2, which depends on
      administrate (~> 0.2.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Administrate 0.3 is required to [support Rails 5](https://github.com/thoughtbot/administrate/blob/master/CHANGELOG.md#030-oct-28-2016), which I am using. 

Any plans to update to the latest version of Administrate? Thanks!

**Comment by bryanbraun** [comment]
I believe this can be closed now that #11 was merged.
