### ISSUE TITLE
REQUESTING NEW MAINTAINER

### ISSUE THREAD

**Issue by eddietejeda** [eddietejeda/administrate-field-json#16]
I notice this project gets a bit of traffic. I don't have time to manage this anymore and this tool is no longer related to my work.

Anyone interested in taking over this project?

**Comment by krainboltgreene** [comment]
Honestly I wish they would just make an administrate-ecosystem. :/

**Comment by volkov-sergey** [comment]
Hi mate. I have created this issue #18
