### ISSUE TITLE
An updated version of this gem, since this one not maintained

### ISSUE THREAD

**Issue by volkov-sergey** [eddietejeda/administrate-field-json#18]
Hello, @eddietejeda! Thanks for your work, mate! Your gem inspired me to create an updated version of JSON editing field for administrate. 

https://github.com/codica2/administrate-field-jsonb

Maybe it can help someone.

Features:
this gem +
+ data transformation
+ jsoneditor on the show page
+ ability to customize show page
+ new administrate version supported

**Comment by eddietejeda** [comment]
Thank you!
