### ISSUE TITLE
administrate-field-json.js not loading

### ISSUE THREAD

**Issue by thebenedict** [eddietejeda/administrate-field-json#4]
Thanks very much for making a json field, exactly what I'm looking for.

On install (Rails 4.2.0, Administrate 0.2.2) the javascript doesn't load for me. I notice that `administrate-field-json.js` is in an administrate-field-json subdirectory of assets, i.e. `/app/assets/javascripts/administrate-field-json/administrate-field-json.js`

So I have to change:

`Administrate::Engine.add_javascript "administrate-field-json"`

to

 `Administrate::Engine.add_javascript "administrate-field-json/administrate-field-json"`

in /lib/administrate/field/json.rb in order to load the javascript.

Is there a reason for the subdirectory, or a different approach you prefer? Removing the subdirectory also fixes the issue for me. Happy to submit a PR with either.

Do you intend to release this under an open source license? Very interested in using and contributing.

**Comment by v-kumar** [comment]
I am running into the same error.

**Comment by thebenedict** [comment]
@v-kumar It looks like @eddietejeda renamed the file last night, make sure you have the latest from master and try again.

I noticed a related issue where this gem's js was being included twice. If you see the same please try my fork: https://github.com/thebenedict/administrate-field-json

You may also need to add these two lines to your app's `config/initializers/assets.rb`:

`Rails.application.config.assets.precompile += %w( administrate-field-json.css )`
`Rails.application.config.assets.precompile += %w( administrate-field-json.js )`

This doesn't seem right but I don't understand the issue yet.

**Comment by eddietejeda** [comment]
@thebenedict thanks for looking into this. I assumed people were working from the release, not master branch. Sorry if it caused problems.

But I have found that naming application.js causes problems with asset pipeline.

I just pushed up a commit that removes the duplicate printing and proper path to .js.

If these fixes works for you all, I would be ready to push 0.0.2 to ruby gems.

**Comment by thebenedict** [comment]
No problems caused, thanks for the reply.

My only concern with the approach is that I need to add this gem's assets to the `config.assets.precompile` list explicitly, in `config/initializers/assets.rb`:

```
Rails.application.config.assets.precompile += %w( administrate-field-json.css )
Rails.application.config.assets.precompile += %w( administrate-field-json.js )
```

Have you found a way around it? The two options I see are

1) To use the `application.js` name per #5 -- this seems to be [the approach @graysonwright takes in administrate-field-nested_has_many](https://github.com/graysonwright/administrate-field-nested_has_many/tree/master/app/assets/javascripts/administrate-field-nested_has_many).

2) To patch Administrate's `Administrate::Engine.add_javascript` and `Administrate::Engine.add_stylesheet` to also add asset names to `config.assets.precompile`. This feels like magic to me so I don't like it as much. For example, in `administrate/lib/administrate/engine.rb`:

```
    def self.add_javascript(script)
      Engine.config.assets.precompile << "#{script}.js"
      @@javascripts << script
    end
```

Can you be more specific about asset pipeline issues caused with the `application.js` name? Happy to try to find a workaround for them, also open to other ideas!

**Comment by eddietejeda** [comment]
Actually, you are correct, and it's not a problem. The conflict I was thinking about was resolved when we switched to using  `Administrate::Engine.add_*`.

I tested the code in a branch on my own app and it worked just fine. I've renamed files and pushed to master.

**Comment by thebenedict** [comment]
Cheers, master works great for me now! Would you be willing to publish this version to RubyGems, and maybe add a license? It would help me a lot.
